server:
	poetry run python server.py --city_name portland --feed_name free-bikes 

client:
	poetry run python client.py

station-data:
	poetry run python server.py --city_name portland --feed_name station_information 

producer:
	poetry run python producer.py 

